CREATE TABLE SPECIALITE
(code INTEGER,
titre VARCHAR2(20) NOT NULL,
description VARCHAR2(20),
CONSTRAINT PK_SPECIALITE PRIMARY KEY (code)
)
/

CREATE TABLE SALLE
(idSalle INTEGER,
nom VARCHAR2(20) NOT NULL,
CONSTRAINT PK_SALLE PRIMARY KEY (idSalle)
)
/

CREATE TABLE CATEGORIES
(IdCategorie INTEGER,
nom VARCHAR2(20) NOT NULL,
Description VARCHAR2(20),
CONSTRAINT PK_CATEGORIES PRIMARY KEY (IdCategorie)
)
/

CREATE TABLE TYPECHIRURGIE
(IdType INTEGER,
nom VARCHAR2(20) NOT NULL,
Description VARCHAR2(200),
CONSTRAINT PK_TYPECHIRURGIE PRIMARY KEY (IdType)
)
/

CREATE TABLE ORDONNANCE
(numOrd INTEGER,
recommandations VARCHAR2(20),
type VARCHAR2(20),
dateC DATE,
nbrMedicaments INTEGER,
CONSTRAINT PK_ORDONNANCE PRIMARY KEY (numOrd),
CONSTRAINT CHK_ORDONNANCE CHECK (type IN ('Chirugie','Médicaments'))
)
/

CREATE TABLE DOCTEUR
(matricule INTEGER,
nomM VARCHAR2(20) NOT NULL,
prenomM VARCHAR2(20) NOT NULL,
specialite INTEGER,
ville VARCHAR2(20),
adresse INTEGER,
niveau VARCHAR2(20),
nbrPatients INTEGER DEFAULT 0,
nbrMoyenMedicaments NUMBER DEFAULT 0,
CONSTRAINT PK_DOCTEUR PRIMARY KEY (matricule),
CONSTRAINT FK_DOCTEUR FOREIGN KEY (specialite) REFERENCES SPECIALITE (code), 
CONSTRAINT CHK2_DOCTEUR CHECK (nbrMoyenMedicaments >=0),
CONSTRAINT CHK3_DOCTEUR CHECK (niveau IN ('Étudiant','Interne','Docteur'))
)
/

CREATE TABLE DOSSIERPATIENT
(numDos INTEGER,
nomP VARCHAR2(20) NOT NULL,
prenomP VARCHAR2 (20) NOT NULL,
sexe VARCHAR2 (1),
numAS INTEGER UNIQUE,
dateNaiss DATE,
dateC DATE,
matricule INTEGER,
nbrConsultation INTEGER DEFAULT 0,
CONSTRAINT PK_DOSSIERPATIENT PRIMARY KEY (numDos),
CONSTRAINT FK_DOSSIERPATIENT FOREIGN KEY (matricule) REFERENCES DOCTEUR (matricule) ON DELETE SET NULL,
CONSTRAINT CHK_DOSSIERPATIENT CHECK (sexe IN ('m','M','f','F')),
CONSTRAINT CHK2_DOSSIERPATIENT CHECK (nbrConsultation >=0)
)
/



CREATE TABLE CONSULTATION
(CodeDocteur INTEGER,
numDos INTEGER,
dateC DATE,
diagnostic VARCHAR2(200) NOT NULL,
numOrd INTEGER,
CONSTRAINT PK_CONSULTATION PRIMARY KEY (CodeDocteur,numDos,dateC),
CONSTRAINT FK_CONSULTATION FOREIGN KEY (CodeDocteur) REFERENCES DOCTEUR (matricule) ON DELETE CASCADE,
CONSTRAINT FK2_CONSULTATION FOREIGN KEY (numOrd) REFERENCES ORDONNANCE (numOrd) NOT DEFERRABLE, 
CONSTRAINT FK3_CONSULTATION FOREIGN KEY (numDos) REFERENCES DOSSIERPATIENT (numDos) ON DELETE CASCADE,
)
/

CREATE TABLE CHIRURGIE
(idChir INTEGER,
idType INTEGER,
idSalle INTEGER,
dateChirurgie DATE,
HeureDebut INTEGER,
HeureFin INTEGER,
CONSTRAINT PK_CHIRURGIE PRIMARY KEY (idChir),
CONSTRAINT FK_CHIRURGIE FOREIGN KEY (idType) REFERENCES TYPECHIRURGIE (idType),
CONSTRAINT FK2_CHIRURGIE FOREIGN KEY (idSalle) REFERENCES SALLE (idSalle),
CONSTRAINT CHK_CHIRURGIE CHECK (HeureDebut >=0),
CONSTRAINT CHK2_CHIRURGIE CHECK (HeureFin >=0)
)
/

CREATE TABLE ORDONNANCECHIRURGIE
(numOrd INTEGER,
idChir INTEGER,
rang INTEGER,
CONSTRAINT PK_ORDONNANCECHIRURGIE PRIMARY KEY (numOrd,idChir),
CONSTRAINT FK_ORDONNANCECHIRURGIE FOREIGN KEY (idChir) REFERENCES CHIRURGIE (idChir),
CONSTRAINT FK2_ORDONNANCECHIRURGIE FOREIGN KEY (numOrd) REFERENCES ORDONNANCE (numOrd)
)
/

CREATE TABLE SPECIALISATIONSALLE
(IdType INTEGER,
idSalle INTEGER, 
dateC DATE,
CONSTRAINT PK_SPECIALISATIONSALLE PRIMARY KEY(IdType,idSalle),
CONSTRAINT FK_SPECIALISATIONSALLE FOREIGN KEY (IdType) REFERENCES TYPECHIRURGIE (IdType),
CONSTRAINT FK2_SPECIALISATIONSALLE FOREIGN KEY (idSalle) REFERENCES SALLE (idSalle)
)
/

CREATE TABLE MEDICAMENT
(idMed INTEGER,
nomMed VARCHAR2(20) NOT NULL,
prix NUMBER (6,2) DEFAULT 0,
categorie INTEGER,
CONSTRAINT PK_MEDICAMENT PRIMARY KEY(idMed),
CONSTRAINT FK_MEDICAMENT FOREIGN KEY(categorie) REFERENCES CATEGORIES (IdCategorie),
CONSTRAINT CHK_MEDICAMENT CHECK (prix >=0)
)
/

CREATE TABLE ORDONNANCEMEDICAMENTS
(numOrd INTEGER,
idMed INTEGER,
nbBoites INTEGER DEFAULT 0,
CONSTRAINT PK_ORDONNANCEMEDICAMENTS PRIMARY KEY(numOrd,idMed),
CONSTRAINT FK_ORDONNANCEMEDICAMENTS FOREIGN KEY(numOrd) REFERENCES ORDONNANCE (numOrd),
CONSTRAINT FK2_ORDONNANCEMEDICAMENTS FOREIGN KEY(idMed) REFERENCES MEDICAMENT (idMed),
CONSTRAINT CHK_ORDONNANCEMEDICAMENTS CHECK (nbBoites >=0)
)
/





