DROP TABLE DOSSIERPATIENT CASCADE CONSTRAINTS PURGE;
DROP TABLE DOCTEUR CASCADE CONSTRAINTS PURGE;
DROP TABLE CONSULTATION CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDONNANCE CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDONNANCECHIRURGIE CASCADE CONSTRAINTS PURGE;
DROP TABLE CHIRURGIE CASCADE CONSTRAINTS PURGE;
DROP TABLE SALLE CASCADE CONSTRAINTS PURGE;
DROP TABLE SPECIALISATIONSALLE CASCADE CONSTRAINTS PURGE;
DROP TABLE TYPECHIRURGIE CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDONNANCEMEDICAMENTS CASCADE CONSTRAINTS PURGE;
DROP TABLE MEDICAMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE SPECIALITE CASCADE CONSTRAINTS PURGE;
DROP TABLE CATEGORIES CASCADE CONSTRAINTS PURGE;

